services:
  dev:
    build: .
    container_name: dev_container
    volumes:
      - .:/workspace:cached
    ports:
      - "8080:8080"
    # Required for Podman in container
    security_opt:
      - label=disable
    devices:
      - /dev/fuse:/dev/fuse:rwm
  
  postgres:
    image: postgres:17.3-bookworm
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
