version: "3.8"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev_container
    volumes:
      - .:/workspace:cached
    # Additional run arguments may be added here
    # Forward any development ports if necessary
    ports:
      - "8080:8080"
  
  postgres:
    image: postgres:17.3-bookworm
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
